# tasks/build_openssl.yml
- name: Download and extract OpenSSL source
  unarchive:
    src: "https://www.openssl.org/source/{{ openssl_version }}.tar.gz"
    dest: "{{ src_dir }}"
    remote_src: yes
  become: true

- name: Build and install OpenSSL
  shell: |
    nice -n1 ./config
    nice -n1 make -j$(nproc)
    nice -n1 make install_sw
  args:
    chdir: "{{ src_dir }}/{{ openssl_version }}"
  become: true
