# tasks/build_pigz.yml
- name: Extract Pigz source
  unarchive:
    src: "https://zlib.net/pigz/pigz.tar.gz"
    dest: "{{ src_dir }}"
    remote_src: yes
  become: true

- name: Build Pigz
  shell: make
  args:
    chdir: "{{ src_dir }}/pigz"
  become: true

- name: Install Pigz binaries
  copy:
    src: "{{ src_dir }}/pigz/pigz"
    dest: /usr/local/bin/pigz
    mode: '0755'
    remote_src: yes
  become: true

- name: Create symlink for unpigz
  file:
    src: /usr/local/bin/pigz
    dest: /usr/local/bin/unpigz
    state: link
  become: true
