# tasks/build_zlib.yml
- name: Extract Zlib source
  unarchive:
    src: "https://www.zlib.net/{{ zlib_version }}.tar.gz"
    dest: "{{ src_dir }}"
    remote_src: yes
  become: true

- name: Build and install Zlib
  shell: |
    ./configure
    make -j$(nproc)
    make install
  args:
    chdir: "{{ src_dir }}/{{ zlib_version }}"
  become: true
