# tasks/build_pcre2.yml
- name: Extract PCRE2 source
  unarchive:
    src: "https://github.com/PCRE2Project/pcre2/releases/download/{{ pcre2_version }}/{{ pcre2_version }}.tar.gz"
    dest: "{{ src_dir }}"
    remote_src: yes
  become: true

- name: Build and install PCRE2
  shell: |
    nice -n1 ./configure
    nice -n1 make -j$(nproc)
    nice -n1 make install
  args:
    chdir: "{{ src_dir }}/{{ pcre2_version }}"
  become: true
