# tasks/cleanup.yml
- name: Remove source directories
  file:
    path: "{{ src_dir }}/{{ item }}"
    state: absent
  loop:
    - "{{ pcre2_version }}"
    - "{{ zlib_version }}"
    - "{{ openssl_version }}"
    - "{{ nginx_version }}"
    - pigz
    - nginx-module-vts
  become: true
