# tasks/clone_nginx_module_vts.yml
- name: Clone nginx-module-vts repository
  git:
    repo: "https://github.com/vozlt/nginx-module-vts"
    dest: "{{ src_dir }}/nginx-module-vts"
    depth: 1
  become: true

- name: install libxslt-dev
  apt:
    name: libxslt-dev
    state: present
  become: true

- name: Clone web-dav-ext module
  git:
    repo: "https://github.com/arut/nginx-dav-ext-module.git"
    dest: "{{ src_dir }}/nginx-dav-ext-module"
    depth: 1
  become: true
