# tasks/configure_nginx.yml
- name: Backup existing /etc/nginx if it exists
  shell: cp -r /etc/nginx /etc/nginx-$(date +%Y-%m-%d)
  args:
    executable: /bin/bash
  when: ansible_stat.exists
  vars:
    ansible_stat: "{{ lookup('ansible.builtin.stat', '/etc/nginx') }}"
  become: true

- name: Deploy nginx.conf
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  become: true

- name: Deploy default server configuration
  template:
    src: default_server.conf.j2
    dest: /etc/nginx/conf.d/default_server.conf
  become: true

- name: Deploy systemd service file for Nginx
  template:
    src: nginx.service.j2
    dest: /etc/systemd/system/nginx.service
  become: true

- name: Enable and start Nginx service
  systemd:
    daemon_reload: true
    name: nginx
    enabled: true
    state: restarted
  become: true
