- block:
    - include_tasks: install_dependencies.yml
    - include_tasks: build_pcre2.yml
    - include_tasks: build_zlib.yml
    - include_tasks: build_openssl.yml
    - include_tasks: build_pigz.yml
    - include_tasks: clone_nginx_modules.yml
    - include_tasks: build_nginx.yml
    - include_tasks: configure_logrotate.yml

- include_tasks: configure_nginx.yml
  tags:
    - configure
- include_tasks: cleanup.yml
  tags:
    - cleanup
